### ISSUE TITLE
Characterlimit

### ISSUE THREAD

**Issue by AlexanderFamler** [stefan-hinterhoelzl/DKE-PR#1]
Kein Zeilenumbruch, zu viele Characters zerstören das Profil

![image](https://user-images.githubusercontent.com/61739405/118655904-47d05d00-b7ea-11eb-9f00-a88899d2f79a.png)

![image](https://user-images.githubusercontent.com/61739405/118656037-6cc4d000-b7ea-11eb-8205-d2bdd097d0dd.png)

**Comment by stefan-hinterhoelzl** [comment]
Fixed
Retesting
